# This file was generated by the docusign_rest:generate_config rake task.
# You can run 'ruby lib/tasks/docusign_task.rb' as many times as you need
# to replace the content of this file with a new config.

require_relative '../lib/docusign_rest'

DocusignRest.configure do |config|
  config.username       = 'billy@mortgageclub.io'
  config.password       = '*dsf3#$sSVd23'
  config.integrator_key = 'MORT-ad25d2f7-4588-4728-976a-81b68bad763a'
  config.account_id     = '8844ba87-7f7e-4a6c-bfdf-3e919b5fee19'
  config.endpoint       = 'https://demo.docusign.net/restapi'
  config.api_version    = 'v2'
end
